feat(ci): unconditionally hide prior formatting PR comments, and only post a new one in case of failure

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -10,13 +10,13 @@ on:
   workflow_dispatch:
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
+  group: ${{ github.workflow }}-${{ github.ref }}-linter
   cancel-in-progress: true
 
 permissions:
   contents: read
   pull-requests: write
-  issues: write
+  # issues: write
 
 jobs:
   format-check:
@@ -52,6 +52,7 @@ jobs:
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
+          set -euo pipefail
           if [ -z $(echo -e "${ALL_CHANGED_FILES[@]}" | tr -d '[:space:]') ]; then
             echo -e '\nNo such files affected!'
             exit 0
@@ -61,26 +62,63 @@ jobs:
             echo "- $file"
           done
           echo
-          npx remark --no-stdout --quiet --frail --silently-ignore $(echo -e "${ALL_CHANGED_FILES[@]}" | tr '\n' ' ')
-
-      - name: ${{ steps.check-fmt.conclusion == 'failure' && '👀 How to fix the formatting? See these suggestions!' || '...' }}
-        env:
-          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
-        if: failure()
-        run: |
-          # Preparations
           FILES="$(echo -e "${ALL_CHANGED_FILES[@]}" | tr '\n' ' ')"
-          BODY="{\"body\":\"To fix the **formatting** issues:\n\n1. Install necessary dependencies: \`npm ci\`\n2. Then, run this command:\n\`\`\`shell\nnpx remark -o --silent --silently-ignore ${FILES}\n\`\`\`\"}"
-          # Comment on the PR
-          curl -s -o /dev/null -L -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            -d "$BODY" \
-            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
-          # Comment right in the actions output
-          echo -e "\nInstall necessary dependencies: \033[31mnpm ci\033[0m"
-          echo -e "Then, run this to fix formatting: \033[31mnpx remark -o --silent --silently-ignore ${FILES}\033[0m"
+          ( # try
+            npm run check:fmt:some -- $FILES
+          ) || ( # catch
+            ERR="$(echo $?)"
+            # Comment right in the actions output
+            echo -e "\nInstall necessary dependencies: \033[31mnpm ci\033[0m"
+            echo -e "Then, run this to fix formatting: \033[31mnpm run fmt:some -- ${FILES}\033[0m"
+            # Prepare a comment on the PR
+            COMMENT="To fix the **formatting** issues:\n\n1. Install necessary dependencies: \`npm ci\`\n2. Then, run this command:\n\`\`\`shell\nnpm run fmt:some -- ${FILES}\n\`\`\`"
+            echo "COMMENT='$COMMENT'" >> "$GITHUB_ENV"
+            # Rethrow the exit code of the failed formatting check
+            exit $ERR
+          )
+
+      - name: Manage PR comments
+        if: ${{ !cancelled() }}
+        env:
+          COMMENT: ${{ env.COMMENT }}
+          SUCCESS: ${{ steps.check-fmt.conclusion == 'failure' && 'false' || 'true' }}
+        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
+        with:
+          script: |
+            const success = JSON.parse(process.env.SUCCESS ?? 'false');
+            const comment_text = process.env.COMMENT ?? '';
+            const comments = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            });
+            for (const comment of comments.data) {
+              if (
+                comment.user.type === 'Bot' &&
+                comment.user.login === 'github-actions[bot]' &&
+                comment.body.startsWith(comment_text.slice(0, 30))
+              ) {
+                await github.rest.graphql(`
+                  mutation {
+                    minimizeComment(input: {
+                      subjectId: "${comment.node_id}",
+                      classifier: ${success ? 'RESOLVED' : 'OUTDATED'}
+                    }) {
+                      clientMutationId
+                    }
+                  }
+                `);
+                await exec.exec('sleep 1s');
+              }
+            }
+            if (!success) {
+              await github.rest.issues.createComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                issue_number: context.issue.number,
+                body: `"${comment_text}"`,
+              });
+            }
 
   spell-check:
     name: "Spelling"
@@ -142,11 +180,9 @@ jobs:
         if: ${{ !cancelled() }}
         run: node scripts/check-redirects.mjs previous
 
-      # NOTE: Re-enable before the release,
-      #       see: https://github.com/ton-org/docs/issues/39
-      # - name: Check redirects against the upstream docs.json structure
-      #   if: ${{ !cancelled() }}
-      #   run: node scripts/check-redirects.mjs upstream
+      - name: Check redirects against the upstream docs.json structure
+        if: ${{ !cancelled() }}
+        run: node scripts/check-redirects.mjs upstream
 
   navigation-check:
     name: "Navigation"
